version: "3.3"
services:
  image:
    build: .
    image: zobees/7daystodie
    tty: true
    stdin_open: true
    environment:
      STEAMCMD_SKIP: "true"
      USER_UID: "1001"
      USER_GID: "1001"
    ports:
      - "26900-26903:26900-26903"
      - "26900-26903:26900-26903/udp"
    volumes:
      - ./data:/data
